# Übung 2.2

**Gruppenname:**

*ESM*

Gehen Sie wie folgt vor:

1. Kopieren Sie jetzt dieses Jupyter Notebook in Ihren Ordner (`Abgaben/Team_WXYZ`)

2. Tragen Sie Ihren Gruppennamen auch ganz oben bei "Name Ihrer Gruppe" ein.

3. Bearbeiten Sie dann dieses Notebook. Falls Sie das Notebook im Browser bearbeiten, vergessen Sie nicht, es regelmäßig zu speichern (z.B. über `Strg + S` oder über `File -> Save and Checkpoint`).

## 2.2 - Pandas

Laden Sie den *Titanic* Datensatz von https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

Sie können den Datensatz entweder herunterladen und mit Pandas einlesen oder direkt mit Pandas laden.

In [2]:
import pandas as pd

data = pd.read_csv("../data/titanic.csv")

data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Geben Sie die Namen der Spalten aus.

In [6]:
cols = data.columns.to_list()

Geben Sie die ersten 5 Zeilen des DataFrames aus.

In [4]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Zählen Sie die fehlenden Werte in jeder Spalte des DataFrames und geben die Anzahl aus

In [9]:
for col in cols:
    count = 0 
    for item in data[col]:
        if pd.isna(item):
            count += 1
    print(f'Missing values in {col} is {count}')

Missing values in PassengerId is 0
Missing values in Survived is 0
Missing values in Pclass is 0
Missing values in Name is 0
Missing values in Sex is 0
Missing values in Age is 177
Missing values in SibSp is 0
Missing values in Parch is 0
Missing values in Ticket is 0
Missing values in Fare is 0
Missing values in Cabin is 687
Missing values in Embarked is 2

Entfernen Sie alle Zeilen, die fehlende Werte enthalten, und vergleichen Sie die Form des Datensatzes vor und nach der Bereinigung.

In [11]:
data_clean = data.dropna()

data_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Füllen Sie die fehlenden Werte in der Spalte "Age" mit dem mittleren Alter auf und überprüfen das Ergebnis.

In [13]:
import numpy as np
mean_age = np.mean(data["Age"])

data["Age"] = [mean_age if pd.isna(age) else age for age in data["Age"]]

Konvertieren Sie die Einträge der Spalte "Survived" von `int` in `bool`.

In [20]:
data["Survived"] = data["Survived"].astype(bool)
data["Survived"].dtype

dtype('bool')

Benennen Sie die Spalten um, indem Sie alle Groß- durch Kleinbuchstaben austauschen.

In [23]:
cols_lower = [col.lower() for col in cols]

data.columns = cols_lower

data

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
815,816,False,1,"Fry, Mr. Richard",F,29.699118,0,0,112058,0.0000,B102,S
806,807,False,1,"Andrews, Mr. Thomas Jr",F,39.000000,0,0,112050,0.0000,A36,S
413,414,False,2,"Cunningham, Mr. Alfred Fleming",F,29.699118,0,0,239853,0.0000,NaN,S
481,482,False,2,"Frost, Mr. Anthony Wood ""Archie""",F,29.699118,0,0,239854,0.0000,NaN,S
302,303,False,3,"Johnson, Mr. William Cahoone Jr",F,19.000000,0,0,LINE,0.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,False,1,"Fortune, Mr. Mark",F,64.000000,1,4,19950,263.0000,C23 C25 C27,S
341,342,True,1,"Fortune, Miss. Alice Elizabeth",F,24.000000,3,2,19950,263.0000,C23 C25 C27,S
737,738,True,1,"Lesurer, Mr. Gustave J",F,35.000000,0,0,PC 17755,512.3292,B101,C
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",F,36.000000,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,True,1,"Ward, Miss. Anna",F,35.000000,0,0,PC 17755,512.3292,NaN,C

Erstellen Sie eine Kopie des DataFrames, die lediglich die Spalten "Age", "Sex" und "Survived" enthält.

In [26]:
data = pd.read_csv("../data/titanic.csv")

data_short = data[["Age","Sex", "Survived"]]

Filtern Sie alle Passagiere, die jünger als 30 sind, aus dem DataFrame heraus.

In [28]:
data_young = data[data["Age"] < 30]

Erstellen Sie eine neue Spalte "adult", mit dem Eintrag `True`, falls die Person mindestes 18 Jahre alt ist.

In [29]:
data["Adult"] = data["Age"] >= 18

 Konvertieren Sie alle Werte in der Spalte "Name" in Großbuchstaben.

In [30]:
data["Name"] = [name.lower() for name in data["Name"]]

 Gruppieren Sie Fahrgäste nach "Pclass" (Fahrgastklasse) und berechnen den durchschnittlichen Fahrpreis ("Fare") für jede Klasse.

In [31]:
data.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

Sortieren Sie das DataFrame bzgl. Fahrpreis ("Fare") in absteigender Reihenfolge und zeigen Sie die ersten 10 Zeilen an.

In [18]:
data = data.sort_values("Fare", ascending=True)

data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
815,816,0,1,"Fry, Mr. Richard",F,29.699118,0,0,112058,0.0,B102,S
806,807,0,1,"Andrews, Mr. Thomas Jr",F,39.000000,0,0,112050,0.0,A36,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",F,29.699118,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",F,29.699118,0,0,239854,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",F,19.000000,0,0,LINE,0.0,NaN,S
271,272,1,3,"Tornquist, Mr. William Henry",F,25.000000,0,0,LINE,0.0,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",F,29.699118,0,0,239853,0.0,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",F,38.000000,0,0,19972,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",F,40.000000,0,0,112059,0.0,B94,S
466,467,0,2,"Campbell, Mr. William",F,29.699118,0,0,239853,0.0,NaN,S

Entfernen Sie doppelte Zeilen aus dem Dataset (falls vorhanden). Geben Sie die Größe des DataFrames vorher und nachher an.

In [16]:
data.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",F,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",F,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",F,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",F,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",F,32.000000,0,0,370376,7.7500,NaN,Q

Ersetzen Sie die Werte in der Spalte "Sex". Ändern Sie "male" in "M" und "female" in "F".

In [15]:
data["Sex"] = ['M' if sex == "male" else 'F' for sex in data["Sex"]]

data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",F,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",F,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",F,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",F,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",F,32.000000,0,0,370376,7.7500,NaN,Q